# Generated by Django 3.0.5 on 2020-05-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20200502_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
