# Generated by Django 3.0.5 on 2020-05-02 20:13

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('age', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=35)),
                ('itype', models.CharField(choices=[('DSH', 'DSH'), ('DMH', 'DMH'), ('DLH', 'DLH')], max_length=4)),
                ('status', models.CharField(choices=[('adopt', 'For adoption'), ('temp', 'Temporary'), ('perm', 'Permanent')], max_length=6)),
                ('arrival_date', models.DateField(default=datetime.date.today)),
                ('arrival_details', models.TextField()),
                ('medical_history', models.TextField()),
                ('vaccinations', models.TextField()),
                ('is_microchipped', models.BooleanField()),
                ('flea_control_date', models.DateField()),
                ('deworming_date', models.DateField()),
                ('fiv_felv_date', models.DateField()),
                ('special_needs', models.TextField()),
                ('personality', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Indoors only'), (2, 'Indoors and outdoor'), (3, 'Lap cat'), (4, 'Mellow'), (5, 'Active'), (6, 'Independent'), (7, 'Shy'), (8, 'Playful'), (9, 'Friendly'), (10, 'Curious'), (11, 'Feisty'), (12, 'Affectionate'), (13, 'Loves attention'), (14, 'Aloof'), (15, 'Swats when over stimulated'), (16, 'Needs quiet home'), (17, 'Likes to be held/picked up'), (18, "Doesn't like tot be held/picked up"), (19, 'Comfortable with other cats'), (20, 'Not comfortable with other cats'), (21, 'Comfortable with dogs'), (22, 'Not comfortable with dogs'), (23, 'Good with younger kids'), (24, 'Good with older kids'), (25, 'Needs a home with adults only'), (26, 'Needs time to get to know and trust you')], max_length=68)),
                ('more_personality', models.TextField()),
                ('comments', models.TextField()),
                ('personal_exp', models.TextField()),
            ],
        ),
    ]
