# Generated by Django 3.0.5 on 2020-05-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='more_personality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='personal_exp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
    ]
