# Generated by Django 3.0.5 on 2020-05-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cat',
        ),
        migrations.AddField(
            model_name='document',
            name='cat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/cat_<django.db.models.fields.IntegerField>'),
        ),
    ]
