# Generated by Django 3.0.5 on 2020-05-08 04:18

import directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20200503_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.TextField(default='oldname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=directory.models.upload_path),
        ),
    ]
