# Generated by Django 3.0.5 on 2020-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20200507_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('adopt', 'For adoption'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=10),
        ),
    ]
