# Generated by Django 3.0.5 on 2020-05-22 15:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20200511_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='personality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Indoors only'), (2, 'Indoors and outdoor'), (3, 'Lap cat'), (4, 'Mellow'), (5, 'Active'), (6, 'Independent'), (7, 'Shy'), (8, 'Playful'), (9, 'Friendly'), (10, 'Curious'), (11, 'Feisty'), (12, 'Affectionate'), (13, 'Loves attention'), (14, 'Aloof'), (15, 'Swats when over stimulated'), (16, 'Needs quiet home'), (17, 'Likes to be held/picked up'), (18, "Doesn't like to be held/picked up"), (19, 'Comfortable with other cats'), (20, 'Not comfortable with other cats'), (21, 'Comfortable with dogs'), (22, 'Not comfortable with dogs'), (23, 'Good with younger kids'), (24, 'Good with older kids'), (25, 'Needs a home with adults only'), (26, 'Needs time to get to know and trust you')], max_length=68),
        ),
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('adopt', 'For adoption'), ('temp', 'Temporary'), ('perm', 'Permanent')], max_length=10),
        ),
    ]
