# Generated by Django 3.0.5 on 2020-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20200522_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('event_type', models.CharField(choices=[('vet', 'Vet Appointment'), ('adoption', 'Adoption Appointment'), ('foster', 'Foster Appointment')], max_length=9)),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
