# Generated by Django 3.0.5 on 2020-05-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='event',
            name='cat',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='directory.Cat'),
            preserve_default=False,
        ),
    ]
