# Generated by Django 3.0.5 on 2020-07-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20200613_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('adopt', 'For adoption'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], max_length=10),
        ),
    ]
