# Generated by Django 3.0.5 on 2020-07-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_auto_20200702_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat_id',
            field=models.CharField(max_length=8),
        ),
    ]
