# Generated by Django 3.0.5 on 2020-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_photo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=4)),
                ('cat_name', models.CharField(max_length=50)),
                ('file_title', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=90)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
