# Generated by Django 3.0.5 on 2020-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('directory', '0019_auto_20200704_0118'), ('directory', '0020_auto_20200705_0755'), ('directory', '0021_auto_20200705_0901'), ('directory', '0022_event_hidden')]

    dependencies = [
        ('directory', '0018_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
