# Generated by Django 3.0.8 on 2020-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_auto_20200704_0118_squashed_0022_event_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
