# Generated by Django 3.0.5 on 2020-07-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_auto_20200704_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebackup',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='filebackup',
            name='cat_name',
        ),
    ]
