# Generated by Django 3.0.8 on 2020-07-06 05:52

import directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20200705_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to=directory.models.photo_path),
        ),
    ]
