# Generated by Django 3.0.5 on 2020-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20200705_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileBackup',
        ),
        migrations.AddField(
            model_name='document',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
