# Generated by Django 3.0.8 on 2020-07-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20200705_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
