# Generated by Django 3.0.5 on 2020-07-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_auto_20200705_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
