# Generated by Django 3.0.8 on 2020-07-08 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_remove_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 7, 7)),
            preserve_default=False,
        ),
    ]
