# Generated by Django 3.0.8 on 2020-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_auto_20200707_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cat',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
