# Generated by Django 3.0.8 on 2020-08-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_auto_20200711_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('vet', 'Vet Appointment'), ('adoption', 'Adoption Appointment'), ('foster', 'Foster Appointment'), ('volunteer', 'Volunteer Training')], max_length=9),
        ),
    ]
